server:
  port: 8082

spring:
  application:
    name: apart-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/youngsaber/dockerfiles.git
          search-paths: config
eureka:
  instance:
    hostname: 127.0.0.1
    preferIpAddress: true
  client:
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://root:203414@${eureka.instance.hostname}:8081/eureka/
